### ISSUE TITLE
trend command output is not in chronological order

### ISSUE THREAD

**Issue by cqueern** [CallMeGreg/gh-language#12]
Thanks for the new feature in [1.3.0](https://github.com/CallMeGreg/gh-language/releases/tag/v1.3.0) that adds a trend command to visualize the frequency of languages per year (based on repo creation date).

Is it expected behavior for the output to be in non-chronological order? See screenshot for the output when I ran 

`gh language trend microsoft`

...where the data goes in this order: 2023, 2021, 2018, 2017, 2015, 2024, 2022, 2020, 2019, 2016, 2014

<img width="411" alt="Screenshot 2024-04-24 at 9 24 38 PM" src="https://github.com/CallMeGreg/gh-language/assets/1588185/1d2ab584-1cb3-4b73-b64a-bf380d3ab4a4">

**Comment by CallMeGreg** [comment]
Great catch! I do sort the repos by creation date before any analysis so let me take a closer look at what's going on. Stay tuned!

**Comment by CallMeGreg** [comment]
@cqueern should be all set in v1.3.1, thanks again for opening the issue 🙇
