### ISSUE TITLE
What's the breakdown by year?

### ISSUE THREAD

**Issue by cqueern** [CallMeGreg/gh-language#3]
The output currently displays the frequency of languages since an organization's inception. 

Would it be possible to add an option to the output that would display the frequency of languages used by year? When this option is invoked the output might look something like the below. The numbers in this example don't add up, just showing a possible way to communicate the relative frequencies over time. 
```
Analyzing organization: AcmeCo
Limiting to 100 repositories.
Returning the top 10 languages.
-----------------------------------------------------
For repos created in 2023
 88 repos (88%) that include the language: HTML
 77 repos (77%) that include the language: Ruby
 17 repos (17%) that include the language: Shell
 16 repos (16%) that include the language: Python
  4 repos ( 4%) that include the language: SCSS
-----------------------------------------------------
For repos created in 2022
 88 repos (88%) that include the language: HTML
 77 repos (77%) that include the language: Dockerfile
 17 repos (17%) that include the language: CSS
 16 repos (16%) that include the language: Java
-----------------------------------------------------
For repos created in 2021
 88 repos (88%) that include the language: HTML
 77 repos (77%) that include the language: C
 17 repos (17%) that include the language: Shell
 16 repos (16%) that include the language: Python
 11 repos (11%) that include the language: C++
```
This would be valuable because it would show an organization's decisions about the languages they're invested in over time.

**Comment by CallMeGreg** [comment]
@cqueern thanks for opening an issue, I like the idea. Do you think it would make more sense to target repo create date or most recent commit date?

For example, if a 5 year old repo is still active today, where do those languages land? 2023 or 2018?

**Comment by cqueern** [comment]
Suggest for now in the first go we keep it simple and just target repo create date.

**Comment by CallMeGreg** [comment]
v1.3.0 now includes a `trend` command to visualize language breakdown by year 🚀
